# .github/workflows/build-and-publish.yml

name: Build, Commit & Publish

on:
  push:
    branches:
      - development
    tags:
      - 'v*.*.*' 


    

permissions:
  contents: write  # allow commit back to repo
  packages: write  # allow publishing to GitHub Packages

jobs:
  # ─────────────────────────────────────────────────────────────────────────────
  build_and_commit:
    name: Build & Commit Dist
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/heads/development')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build shared-schemas
        run: npm run build

      - name: Commit built files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: development
          file_pattern: "dist/*"
          commit_message: "chore: auto-build dist on push"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"

  # ─────────────────────────────────────────────────────────────────────────────
  publish_package:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: build_and_commit
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js for publish
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com

      - name: Authenticate to GitHub Packages
        run: npm config set //npm.pkg.github.com/:_authToken="${{ secrets.GITHUB_TOKEN }}"

      - name: Install dependencies
        run: npm ci

      - name: Build shared-schemas (ensure dist is up-to-date)
        run: npm run build

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT_FOR_SHARED_SCHEMAS }}
